Name = str(input("Please what is your Name: "))
Age = int(input("Please what is your Age: "))
Height = float(input("Please what is your Height in metres: "))
Number = int(input("Please what is your Favourite Number: "))
Height_cm =int(Height * 100)
# Print formatted profile card
print("\n================================")
print(f"{'YOUR PROFILE CARD':^32}")
print("================================")
print(f"{'Name:':<18}{Name}")
print(f"{'Age:':<18}{Age} years")
print(f"{'Height:':<18}{Height:.2f}m ({Height_cm:.0f}cm)")
print(f"{'Favourite Number:':<18}{Number}")
print("================================")
